name: Java CI with Coverage

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-and-coverage:
    name: Run Tests and Generate Coverage
    runs-on: ubuntu-latest
    permissions:
      contents: write
      checks: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Run tests with JaCoCo
        run: |
          mvn clean test jacoco:report

      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: target/site/jacoco/jacoco.csv
          badges-directory: badges

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: |
            target/site/jacoco/
            badges/

      - name: Commit and push coverage badges
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add badges/
          git diff --staged --quiet || git commit -m "Update coverage badges [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  coverage-summary:
    name: Coverage summary
    runs-on: ubuntu-latest
    needs: test-and-coverage
    if: always()

    steps:
      - name: Download coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: jacoco-report

      - name: Display coverage summary
        run: |
          echo "=== Coverage Report ==="
          if [[ -f "target/site/jacoco/jacoco.csv" ]]; then
            echo  echo "Coverage reports generated successfully"
            echo "HTML report: target/site/jacoco/index.html"
          else
            echo "No coverage data found"
          fi
